jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: Api/Havira.API

      - name: Publish
        run: dotnet publish -c Release -o published
        working-directory: Api/Havira.API

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: published
          path: Api/Havira.API/published/**